# Generated by Django 3.0 on 2020-02-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='title_img',
            field=models.ImageField(default=0, upload_to='article_title_img/%Y%m%d/'),
            preserve_default=False,
        ),
    ]
