# Generated by Django 3.0 on 2020-02-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20200203_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='title_img',
            field=models.ImageField(upload_to='article_title_img/%Y%m%d/'),
        ),
    ]
