# Generated by Django 3.0 on 2020-02-03 12:40

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20200203_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='title_img',
            field=imagekit.models.fields.ProcessedImageField(upload_to='article_title_img/%Y%m%d/', verbose_name='标题图片'),
        ),
    ]
