# Generated by Django 3.0 on 2020-02-04 13:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_auto_20200203_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='body',
            field=ckeditor.fields.RichTextField(verbose_name='正文'),
        ),
    ]
