# Generated by Django 3.0 on 2020-02-05 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_auto_20200204_2100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlepost',
            options={'ordering': ('-updated',)},
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='body',
            field=models.TextField(verbose_name='正文'),
        ),
    ]
