# Generated by Django 3.0 on 2020-02-05 01:42

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_auto_20200205_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='author_img',
            field=imagekit.models.fields.ProcessedImageField(default='article_title_img/蛋黄君01.jpg', upload_to='article_title_img/%Y%m%d/', verbose_name='头像图片'),
        ),
    ]
