# Generated by Django 3.0 on 2020-02-06 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0015_articlepost_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='点赞量'),
        ),
        migrations.AddField(
            model_name='articlepost',
            name='looks',
            field=models.IntegerField(default=0, verbose_name='浏览量'),
        ),
    ]
